//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinnt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class Language : global::System.Configuration.ApplicationSettingsBase {
        
        private static Language defaultInstance = ((Language)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Language())));
        
        public static Language Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EN_US")]
        public string _LanguageCode {
            get {
                return ((string)(this["_LanguageCode"]));
            }
            set {
                this["_LanguageCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Edit")]
        public string EditMenu {
            get {
                return ((string)(this["EditMenu"]));
            }
            set {
                this["EditMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Find")]
        public string FindMenuItem {
            get {
                return ((string)(this["FindMenuItem"]));
            }
            set {
                this["FindMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Replace")]
        public string ReplaceMenuItem {
            get {
                return ((string)(this["ReplaceMenuItem"]));
            }
            set {
                this["ReplaceMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Isolate")]
        public string IsolateMenuItem {
            get {
                return ((string)(this["IsolateMenuItem"]));
            }
            set {
                this["IsolateMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sub&tract")]
        public string SubtractMenuItem {
            get {
                return ((string)(this["SubtractMenuItem"]));
            }
            set {
                this["SubtractMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inse&rt")]
        public string InsertMenuItem {
            get {
                return ((string)(this["InsertMenuItem"]));
            }
            set {
                this["InsertMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Remove letters")]
        public string RemoveLettersMenuItem {
            get {
                return ((string)(this["RemoveLettersMenuItem"]));
            }
            set {
                this["RemoveLettersMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Change case")]
        public string ChangeCaseMenuItem {
            get {
                return ((string)(this["ChangeCaseMenuItem"]));
            }
            set {
                this["ChangeCaseMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S&pecial characters")]
        public string SpecialCharactersMenuItem {
            get {
                return ((string)(this["SpecialCharactersMenuItem"]));
            }
            set {
                this["SpecialCharactersMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undo")]
        public string UndoMenuItem {
            get {
                return ((string)(this["UndoMenuItem"]));
            }
            set {
                this["UndoMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data")]
        public string DataMenu {
            get {
                return ((string)(this["DataMenu"]));
            }
            set {
                this["DataMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hash")]
        public string HashMenuItem {
            get {
                return ((string)(this["HashMenuItem"]));
            }
            set {
                this["HashMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Convert")]
        public string ConvertMenuItem {
            get {
                return ((string)(this["ConvertMenuItem"]));
            }
            set {
                this["ConvertMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Random")]
        public string RandomMenuItem {
            get {
                return ((string)(this["RandomMenuItem"]));
            }
            set {
                this["RandomMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C&ovfefeize")]
        public string CovfefeizeMenuItem {
            get {
                return ((string)(this["CovfefeizeMenuItem"]));
            }
            set {
                this["CovfefeizeMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Add random letters")]
        public string AddRandomLettrMenuItem {
            get {
                return ((string)(this["AddRandomLettrMenuItem"]));
            }
            set {
                this["AddRandomLettrMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sortation")]
        public string SortationMenu {
            get {
                return ((string)(this["SortationMenu"]));
            }
            set {
                this["SortationMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Sort")]
        public string SortMenuItem {
            get {
                return ((string)(this["SortMenuItem"]));
            }
            set {
                this["SortMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shuff&le")]
        public string ShuffleMenuItem {
            get {
                return ((string)(this["ShuffleMenuItem"]));
            }
            set {
                this["ShuffleMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reverse")]
        public string ReverseMenuItem {
            get {
                return ((string)(this["ReverseMenuItem"]));
            }
            set {
                this["ReverseMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings")]
        public string SettingsMenu {
            get {
                return ((string)(this["SettingsMenu"]));
            }
            set {
                this["SettingsMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Font")]
        public string FontMenuItem {
            get {
                return ((string)(this["FontMenuItem"]));
            }
            set {
                this["FontMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Options")]
        public string OptionsMenuItem {
            get {
                return ((string)(this["OptionsMenuItem"]));
            }
            set {
                this["OptionsMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("About")]
        public string AboutMenuItem {
            get {
                return ((string)(this["AboutMenuItem"]));
            }
            set {
                this["AboutMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("caps")]
        public string ArgCaseCapital {
            get {
                return ((string)(this["ArgCaseCapital"]));
            }
            set {
                this["ArgCaseCapital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lower")]
        public string ArgCaseLower {
            get {
                return ((string)(this["ArgCaseLower"]));
            }
            set {
                this["ArgCaseLower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sentence")]
        public string ArgCaseSentence {
            get {
                return ((string)(this["ArgCaseSentence"]));
            }
            set {
                this["ArgCaseSentence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-sentence")]
        public string ArgCaseRevSentence {
            get {
                return ((string)(this["ArgCaseRevSentence"]));
            }
            set {
                this["ArgCaseRevSentence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sha256")]
        public string ArgSha256Hash {
            get {
                return ((string)(this["ArgSha256Hash"]));
            }
            set {
                this["ArgSha256Hash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sha512")]
        public string ArgSha512Hash {
            get {
                return ((string)(this["ArgSha512Hash"]));
            }
            set {
                this["ArgSha512Hash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("md5")]
        public string ArgMd5Hash {
            get {
                return ((string)(this["ArgMd5Hash"]));
            }
            set {
                this["ArgMd5Hash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ascii")]
        public string ArgAscii {
            get {
                return ((string)(this["ArgAscii"]));
            }
            set {
                this["ArgAscii"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bin")]
        public string ArgBinary {
            get {
                return ((string)(this["ArgBinary"]));
            }
            set {
                this["ArgBinary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hex")]
        public string ArgHexadecimal {
            get {
                return ((string)(this["ArgHexadecimal"]));
            }
            set {
                this["ArgHexadecimal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bcdfghjklmnpqrstvwxyz")]
        public string CovfefeizeConsonants {
            get {
                return ((string)(this["CovfefeizeConsonants"]));
            }
            set {
                this["CovfefeizeConsonants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aeiou")]
        public string CovfefeizeVowels {
            get {
                return ((string)(this["CovfefeizeVowels"]));
            }
            set {
                this["CovfefeizeVowels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("General")]
        public string SettingsGeneralTab {
            get {
                return ((string)(this["SettingsGeneralTab"]));
            }
            set {
                this["SettingsGeneralTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Personalization")]
        public string SettingsPersonalTab {
            get {
                return ((string)(this["SettingsPersonalTab"]));
            }
            set {
                this["SettingsPersonalTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Version: Cinnt v")]
        public string SettingsVersionLabel {
            get {
                return ((string)(this["SettingsVersionLabel"]));
            }
            set {
                this["SettingsVersionLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report an issue")]
        public string SettingsReportIssueLabel {
            get {
                return ((string)(this["SettingsReportIssueLabel"]));
            }
            set {
                this["SettingsReportIssueLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Github")]
        public string SettingsGithubLabel {
            get {
                return ((string)(this["SettingsGithubLabel"]));
            }
            set {
                this["SettingsGithubLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Word wrap")]
        public string SettingsWordWrapCheckBox {
            get {
                return ((string)(this["SettingsWordWrapCheckBox"]));
            }
            set {
                this["SettingsWordWrapCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Max letters (/1024)")]
        public string SettingsMaxLetters {
            get {
                return ((string)(this["SettingsMaxLetters"]));
            }
            set {
                this["SettingsMaxLetters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alphabet")]
        public string SettingsAlphabet {
            get {
                return ((string)(this["SettingsAlphabet"]));
            }
            set {
                this["SettingsAlphabet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"26-letter Latin
26-letter Latin (with capitals)
Russian Cyrillic
Russian Cyrillic (with capitals)
Arabic (Standard)
Devanagari
Japanese (hiragana)
Japanese (katakana)
Japanese (hiragana+katakana)
Syriac
Armenian
Armenian (with capitals)
Georgian (mkhedruli)
Ge'ez
Cree
Inuktitut
Cherokee
Greek
Greek (with capitals)
Mandaic
Vai")]
        public string SettingsAlphabetSelectDropdownBox {
            get {
                return ((string)(this["SettingsAlphabetSelectDropdownBox"]));
            }
            set {
                this["SettingsAlphabetSelectDropdownBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Localization: ")]
        public string SettingsLocalizationLabel {
            get {
                return ((string)(this["SettingsLocalizationLabel"]));
            }
            set {
                this["SettingsLocalizationLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select")]
        public string SettingsLocalizationSelect {
            get {
                return ((string)(this["SettingsLocalizationSelect"]));
            }
            set {
                this["SettingsLocalizationSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Textbox background\r\nTextbox foreground\r\nInactive button background\r\nSelected butt" +
            "on background\r\nActive button background\r\nButton text color\r\nWindow background\r\nF" +
            "ind and replace match color\r\nStatus strip background")]
        public string SettingsPersonalizationText {
            get {
                return ((string)(this["SettingsPersonalizationText"]));
            }
            set {
                this["SettingsPersonalizationText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Modify")]
        public string SettingsModify {
            get {
                return ((string)(this["SettingsModify"]));
            }
            set {
                this["SettingsModify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Change UI Font")]
        public string SettingsChangeUIFont {
            get {
                return ((string)(this["SettingsChangeUIFont"]));
            }
            set {
                this["SettingsChangeUIFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reset")]
        public string SettingsReset {
            get {
                return ((string)(this["SettingsReset"]));
            }
            set {
                this["SettingsReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apply")]
        public string SettingsApply {
            get {
                return ((string)(this["SettingsApply"]));
            }
            set {
                this["SettingsApply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Change Font")]
        public string CharBrowseChangeFont {
            get {
                return ((string)(this["CharBrowseChangeFont"]));
            }
            set {
                this["CharBrowseChangeFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OK")]
        public string Ok {
            get {
                return ((string)(this["Ok"]));
            }
            set {
                this["Ok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cinnt")]
        public string Title {
            get {
                return ((string)(this["Title"]));
            }
            set {
                this["Title"] = value;
            }
        }
    }
}
