//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinnt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinnt.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add random letters.
        /// </summary>
        internal static string AddRandomLettersMenuItem {
            get {
                return ResourceManager.GetString("AddRandomLettersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ascii.
        /// </summary>
        internal static string ArgAscii {
            get {
                return ResourceManager.GetString("ArgAscii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bin.
        /// </summary>
        internal static string ArgBinary {
            get {
                return ResourceManager.GetString("ArgBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caps.
        /// </summary>
        internal static string ArgCaseCapital {
            get {
                return ResourceManager.GetString("ArgCaseCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower.
        /// </summary>
        internal static string ArgCaseLower {
            get {
                return ResourceManager.GetString("ArgCaseLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -sentence.
        /// </summary>
        internal static string ArgCaseRevSentence {
            get {
                return ResourceManager.GetString("ArgCaseRevSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sentence.
        /// </summary>
        internal static string ArgCaseSentence {
            get {
                return ResourceManager.GetString("ArgCaseSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hex.
        /// </summary>
        internal static string ArgHexadecimal {
            get {
                return ResourceManager.GetString("ArgHexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to md5.
        /// </summary>
        internal static string ArgMd5Hash {
            get {
                return ResourceManager.GetString("ArgMd5Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha256.
        /// </summary>
        internal static string ArgSha256Hash {
            get {
                return ResourceManager.GetString("ArgSha256Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha512.
        /// </summary>
        internal static string ArgSha512Hash {
            get {
                return ResourceManager.GetString("ArgSha512Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string CanCovfefeize {
            get {
                return ResourceManager.GetString("CanCovfefeize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change case.
        /// </summary>
        internal static string ChangeCaseMenuItem {
            get {
                return ResourceManager.GetString("ChangeCaseMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font.
        /// </summary>
        internal static string CharBrowseChangeFont {
            get {
                return ResourceManager.GetString("CharBrowseChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string ConvertMenuItem {
            get {
                return ResourceManager.GetString("ConvertMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bcdfghijklmnpqrstvwxyz.
        /// </summary>
        internal static string CovfefeizeConsonants {
            get {
                return ResourceManager.GetString("CovfefeizeConsonants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ovfefeize.
        /// </summary>
        internal static string CovfefeizeMenuItem {
            get {
                return ResourceManager.GetString("CovfefeizeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aeiou.
        /// </summary>
        internal static string CovfefeizeVowels {
            get {
                return ResourceManager.GetString("CovfefeizeVowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DataMenu {
            get {
                return ResourceManager.GetString("DataMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IPA characters.
        /// </summary>
        internal static string EnterIpaMenuItem {
            get {
                return ResourceManager.GetString("EnterIpaMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find.
        /// </summary>
        internal static string FindMenuItem {
            get {
                return ResourceManager.GetString("FindMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string FontMenuItem {
            get {
                return ResourceManager.GetString("FontMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        internal static string HashMenuItem {
            get {
                return ResourceManager.GetString("HashMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inse&amp;rt.
        /// </summary>
        internal static string InsertMenuItem {
            get {
                return ResourceManager.GetString("InsertMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Isolate.
        /// </summary>
        internal static string IsolateMenuItem {
            get {
                return ResourceManager.GetString("IsolateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (U.S.).
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsMenuItem {
            get {
                return ResourceManager.GetString("OptionsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string RandomMenu {
            get {
                return ResourceManager.GetString("RandomMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove letters.
        /// </summary>
        internal static string RemoveLettersMenuItem {
            get {
                return ResourceManager.GetString("RemoveLettersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string ReplaceMenuItem {
            get {
                return ResourceManager.GetString("ReplaceMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string ReverseMenuItem {
            get {
                return ResourceManager.GetString("ReverseMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet.
        /// </summary>
        internal static string SettingsAlphabet {
            get {
                return ResourceManager.GetString("SettingsAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26-letter Latin
        ///26-letter Latin (with capitals)
        ///Russian Cyrillic
        ///Russian Cyrillic (with capitals)
        ///Arabic (Standard)
        ///Devanagari
        ///Japanese (hiragana)
        ///Japanese (katakana)
        ///Japanese (hiragana+katakana)
        ///Syriac
        ///Armenian
        ///Armenian (with capitals)
        ///Georgian (mkhedruli)
        ///Ge&apos;ez
        ///Cree
        ///Inuktitut
        ///Cherokee
        ///Greek
        ///Greek (with capitals)
        ///Mandaic
        ///Vai.
        /// </summary>
        internal static string SettingsAlphabetSelectDropdownBox {
            get {
                return ResourceManager.GetString("SettingsAlphabetSelectDropdownBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string SettingsApply {
            get {
                return ResourceManager.GetString("SettingsApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change UI Font.
        /// </summary>
        internal static string SettingsChangeUIFont {
            get {
                return ResourceManager.GetString("SettingsChangeUIFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsGeneralTab {
            get {
                return ResourceManager.GetString("SettingsGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        internal static string SettingsGithubLabel {
            get {
                return ResourceManager.GetString("SettingsGithubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization:.
        /// </summary>
        internal static string SettingsLocalizationLabel {
            get {
                return ResourceManager.GetString("SettingsLocalizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SettingsLocalizationSelect {
            get {
                return ResourceManager.GetString("SettingsLocalizationSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max letters (/1024).
        /// </summary>
        internal static string SettingsMaxLetters {
            get {
                return ResourceManager.GetString("SettingsMaxLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string SettingsModify {
            get {
                return ResourceManager.GetString("SettingsModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox background
        ///Textbox foreground
        ///Inactive button background
        ///Selected button background
        ///Active button background
        ///Button text color
        ///Window background
        ///Find and replace match color
        ///Status strip background.
        /// </summary>
        internal static string SettingsPersonalizationText {
            get {
                return ResourceManager.GetString("SettingsPersonalizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string SettingsPersonalTab {
            get {
                return ResourceManager.GetString("SettingsPersonalTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        internal static string SettingsReportIssueLabel {
            get {
                return ResourceManager.GetString("SettingsReportIssueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: Cinnt v.
        /// </summary>
        internal static string SettingsVersionLabel {
            get {
                return ResourceManager.GetString("SettingsVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word wrap.
        /// </summary>
        internal static string SettingsWordWrapCheckBox {
            get {
                return ResourceManager.GetString("SettingsWordWrapCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuff&amp;le.
        /// </summary>
        internal static string ShuffleMenuItem {
            get {
                return ResourceManager.GetString("ShuffleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortation.
        /// </summary>
        internal static string SortationMenu {
            get {
                return ResourceManager.GetString("SortationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sort.
        /// </summary>
        internal static string SortMenuItem {
            get {
                return ResourceManager.GetString("SortMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;pecial characters.
        /// </summary>
        internal static string SpecialCharactersMenuItem {
            get {
                return ResourceManager.GetString("SpecialCharactersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub&amp;tract.
        /// </summary>
        internal static string SubtractMenuItem {
            get {
                return ResourceManager.GetString("SubtractMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinnt.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UndoMenuItem {
            get {
                return ResourceManager.GetString("UndoMenuItem", resourceCulture);
            }
        }
    }
}
